Mappings: 
  AmiRegionMap: 
    us-east-1: 
      AMI: "ami-0440d3b780d96b29d"
    us-east-2: 
      AMI: "ami-02ca28e7c7b8f8be1"
    us-west-1: 
      AMI: "ami-07619059e86eaaaa2"
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["-", [demo, instance, from, cloudformation]]
      SecurityGroups:
        - !Ref DemoSG

  DemoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from Anywhere-IPv4
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0    