AWSTemplateFormatVersion: 2010-09-09
Description: My first template in AWS CloudFormation Step by Step
Resources:
  SampleTopic:
    Type: AWS::SNS::Topic
    DependsOn: WebServerInstance

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03d8b47244d950bbb
      InstanceType: t2.micro
      SubnetId: subnet-0619479663b4084af
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: web-server
        - Key: Project
          Value: AWS CloudFormation Step by Step

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers
      VpcId: vpc-0b0c8badfef0024a4
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
